### ISSUE TITLE
tw2panda CLI - let's work together ?

### ISSUE THREAD

**Issue by astahmer** [jherr/tw2panda-cli#1]
Hey ! I'm impressed by how fast you made this ! Especially with the VSCode extension, I also had that in mind (and it's been asked [just 3 hours ago](https://github.com/chakra-ui/panda/discussions/1080) !) so I'm super happy to see there is an actual need for that ! 

Maybe you didn't see but the [tw2panda repo](https://github.com/astahmer/tw2panda) repo went through a [huge refactor](https://github.com/astahmer/tw2panda/commit/ccdfc419d24755f0f992bc83171274ed9346a43c) in the last days, including a split between [the online app](https://tw2panda-astahmer.vercel.app/) & the core (+ new CLI !)

Since it's now properly decoupled, I published the [`tw2panda npm`](https://npmjs.com/package/tw2panda) package that exports all the function that you need to get the same logic as the online app

The core (exported functions) already has lots of tests, handles [`class-variance-authority`](https://cva.style/docs) conversion to panda's [`cva`](https://panda-css.com/docs/concepts/recipes#atomic-recipe-or-cva) function & the CLI allow using a custom `panda.config.xxx` and a custom `tailwind.config.xxx` file to get the best conversion result

It actually has:
- a `rewrite` command that returns the converted file output to stdout (or write to disk with a `-w` flag)
- an `extract` command that returns the list of tw classes + their style object equivalent
- a `convert` command that only convert a string of tailwind class and return the style object equivalent

From a quick look, it seems your explain command is very similar to what I had made in the online app
![Screenshot 2023-07-21 at 20 32 02](https://github.com/jherr/tw2panda-cli/assets/47224540/1fb146d9-b7fa-4bf2-9e7d-401df5b62edd), I think it's a great idea to include it in the extension ! 
Also, one thing you have that I don't, is the automatic transform to patterns (like [here](https://youtu.be/fKSemrudovo?t=442) `hstack`)

So I'm wondering if you'd like to join efforts and collaborate on the `tw2panda` package (& possibly the VSCode extension) ?

**Comment by jherr** [comment]
Wonder twin power activate! Let's join forces! And I'm happy to make this just a pointer to your repo. If we can get the `explain` and the `patterns` and maybe the CTA (if it isn't in there already) then that would be AWESOME!
